//! 全局/小说 `.env` 与 `~/.inkoswin/settings.json`（对齐 `inkoswin.config_store`）。

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

pub const ENV_KEYS: [(&str, &str); 7] = [
    ("provider", "INKOS_LLM_PROVIDER"),
    ("base_url", "INKOS_LLM_BASE_URL"),
    ("api_key", "INKOS_LLM_API_KEY"),
    ("model", "INKOS_LLM_MODEL"),
    ("temperature", "INKOS_LLM_TEMPERATURE"),
    ("max_tokens", "INKOS_LLM_MAX_TOKENS"),
    ("thinking_budget", "INKOS_LLM_THINKING_BUDGET"),
];

pub const FIELD_LABELS_CN: [(&str, &str); 7] = [
    ("provider", "Provider"),
    ("base_url", "Base URL"),
    ("api_key", "API Key"),
    ("model", "Model"),
    ("temperature", "Temperature"),
    ("max_tokens", "Max Tokens"),
    ("thinking_budget", "Thinking Budget"),
];

fn known_env_keys() -> HashSet<&'static str> {
    ENV_KEYS.iter().map(|(_, k)| *k).collect()
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct LlmConfig {
    pub provider: String,
    pub base_url: String,
    pub api_key: String,
    pub model: String,
    pub temperature: String,
    pub max_tokens: String,
    pub thinking_budget: String,
}

impl LlmConfig {
    pub fn resolved_with(&self, fallback: &LlmConfig) -> LlmConfig {
        let pick = |a: &str, b: &str| {
            let x = a.trim();
            if x.is_empty() {
                b.trim().to_string()
            } else {
                x.to_string()
            }
        };
        LlmConfig {
            provider: pick(&self.provider, &fallback.provider),
            base_url: pick(&self.base_url, &fallback.base_url),
            api_key: pick(&self.api_key, &fallback.api_key),
            model: pick(&self.model, &fallback.model),
            temperature: pick(&self.temperature, &fallback.temperature),
            max_tokens: pick(&self.max_tokens, &fallback.max_tokens),
            thinking_budget: pick(&self.thinking_budget, &fallback.thinking_budget),
        }
    }

    pub fn to_env_map(&self) -> HashMap<String, String> {
        let mut m = HashMap::new();
        let pairs = [
            ("INKOS_LLM_PROVIDER", &self.provider),
            ("INKOS_LLM_BASE_URL", &self.base_url),
            ("INKOS_LLM_API_KEY", &self.api_key),
            ("INKOS_LLM_MODEL", &self.model),
            ("INKOS_LLM_TEMPERATURE", &self.temperature),
            ("INKOS_LLM_MAX_TOKENS", &self.max_tokens),
            ("INKOS_LLM_THINKING_BUDGET", &self.thinking_budget),
        ];
        for (k, v) in pairs {
            if !v.trim().is_empty() {
                m.insert(k.to_string(), v.trim().to_string());
            }
        }
        m
    }
}

pub fn config_from_env(data: &HashMap<String, String>) -> LlmConfig {
    let g = |key: &str| -> String { data.get(key).cloned().unwrap_or_default() };
    LlmConfig {
        provider: g("INKOS_LLM_PROVIDER"),
        base_url: g("INKOS_LLM_BASE_URL"),
        api_key: g("INKOS_LLM_API_KEY"),
        model: g("INKOS_LLM_MODEL"),
        temperature: g("INKOS_LLM_TEMPERATURE"),
        max_tokens: g("INKOS_LLM_MAX_TOKENS"),
        thinking_budget: g("INKOS_LLM_THINKING_BUDGET"),
    }
}

pub fn parse_env_file(path: &Path) -> HashMap<String, String> {
    let Ok(raw) = fs::read_to_string(path) else {
        return HashMap::new();
    };
    let mut data = HashMap::new();
    for line in raw.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        data.insert(
            k.trim().to_string(),
            parse_env_value(v.trim()).to_string(),
        );
    }
    data
}

fn parse_env_value(value: &str) -> String {
    let bytes = value.as_bytes();
    if bytes.len() >= 2 {
        let q = bytes[0];
        if (q == b'"' || q == b'\'') && bytes[bytes.len() - 1] == q {
            let inner = &value[1..value.len() - 1];
            return inner.replace("\\\"", "\"").replace("\\\\", "\\");
        }
    }
    value.to_string()
}

fn format_env_value(value: &str) -> String {
    if value.is_empty() {
        return String::new();
    }
    let needs_quote = value.chars().any(|c| c.is_whitespace())
        || value.contains('#')
        || value.starts_with('"')
        || value.starts_with('\'');
    if needs_quote {
        let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        value.to_string()
    }
}

pub fn write_env_file(path: &Path, data: &HashMap<String, String>) -> Result<()> {
    let known = known_env_keys();
    let mut lines: Vec<String> = vec![
        "# Generated by InkOS Desktop.".to_string(),
        "# Novel-level .env overrides ~/.inkos/.env when in a novel directory.".to_string(),
        String::new(),
    ];

    for (_, env_key) in ENV_KEYS.iter() {
        if let Some(v) = data.get(*env_key) {
            if !v.trim().is_empty() {
                lines.push(format!("{env_key}={}", format_env_value(v.trim())));
            }
        }
    }

    let mut extras: Vec<_> = data
        .iter()
        .filter(|(k, v)| !known.contains(k.as_str()) && !v.trim().is_empty())
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    extras.sort_by(|a, b| a.0.cmp(&b.0));
    if !extras.is_empty() {
        lines.push(String::new());
        lines.push("# Preserved extra keys".to_string());
        for (k, v) in extras {
            lines.push(format!("{k}={}", format_env_value(v.trim())));
        }
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create_dir_all {:?}", parent))?;
    }
    let out = lines.join("\n").trim_end().to_string() + "\n";
    fs::write(path, out).with_context(|| format!("write {:?}", path))?;
    Ok(())
}

pub fn merge_effective_rows(global: &LlmConfig, novel: &LlmConfig) -> Vec<(String, String, String)> {
    let keys = [
        "provider",
        "base_url",
        "api_key",
        "model",
        "temperature",
        "max_tokens",
        "thinking_budget",
    ];
    let mut rows = Vec::new();
    for (i, key) in keys.iter().enumerate() {
        let nv = field_by_key(novel, key);
        let gv = field_by_key(global, key);
        let (val, src) = if !nv.trim().is_empty() {
            (nv, "小说配置")
        } else if !gv.trim().is_empty() {
            (gv, "全局配置")
        } else {
            (String::new(), "未设置")
        };
        let label = FIELD_LABELS_CN[i].1.to_string();
        rows.push((label, val, src.to_string()));
    }
    rows
}

fn field_by_key(c: &LlmConfig, key: &str) -> String {
    match key {
        "provider" => c.provider.clone(),
        "base_url" => c.base_url.clone(),
        "api_key" => c.api_key.clone(),
        "model" => c.model.clone(),
        "temperature" => c.temperature.clone(),
        "max_tokens" => c.max_tokens.clone(),
        "thinking_budget" => c.thinking_budget.clone(),
        _ => String::new(),
    }
}

pub fn mask_secret(value: &str) -> String {
    let cleaned = value.trim();
    if cleaned.is_empty() {
        return String::new();
    }
    let chars: Vec<char> = cleaned.chars().collect();
    if chars.len() <= 8 {
        return "*".repeat(chars.len());
    }
    let head: String = chars.iter().take(4).collect();
    let tail: String = chars.iter().rev().take(4).rev().collect();
    format!("{head}...{tail}")
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct VendorConfig {
    #[serde(default)]
    pub base_url: String,
    #[serde(default)]
    pub api_key: String,
    #[serde(default)]
    pub model: String,
    #[serde(default)]
    pub temperature: String,
    #[serde(default)]
    pub max_tokens: String,
    #[serde(default)]
    pub thinking_budget: String,
}

impl VendorConfig {
    pub fn is_configured(&self) -> bool {
        !self.base_url.trim().is_empty()
            && !self.model.trim().is_empty()
            && (!self.api_key.trim().is_empty() || self.base_url.contains("localhost"))
    }

    /// 把一个 `LlmConfig`（例如来自 `.env`）拷贝成 `VendorConfig`。
    /// `provider` 字段被丢弃（VendorConfig 不使用）。
    pub fn from_llm(c: &LlmConfig) -> Self {
        Self {
            base_url: c.base_url.trim().to_string(),
            api_key: c.api_key.trim().to_string(),
            model: c.model.trim().to_string(),
            temperature: c.temperature.trim().to_string(),
            max_tokens: c.max_tokens.trim().to_string(),
            thinking_budget: c.thinking_budget.trim().to_string(),
        }
    }

    /// 把另一个 `LlmConfig` 中的非空字段覆盖到 self（项目级 .env 覆盖 Studio vendor）。
    /// `provider` 字段不参与覆盖（VendorConfig 没有 provider）。
    pub fn overlay_llm(&mut self, other: &LlmConfig) {
        let put = |dst: &mut String, src: &str| {
            let t = src.trim();
            if !t.is_empty() {
                *dst = t.to_string();
            }
        };
        put(&mut self.base_url, &other.base_url);
        put(&mut self.api_key, &other.api_key);
        put(&mut self.model, &other.model);
        put(&mut self.temperature, &other.temperature);
        put(&mut self.max_tokens, &other.max_tokens);
        put(&mut self.thinking_budget, &other.thinking_budget);
    }
}

/// 根据 base_url 粗略匹配一个内置 vendor 预设 id；匹配不到返回 `"custom"`。
///
/// 规则：
/// - 非空 base_url → 先找与任一预设 `base_url` 前缀相同的预设；
/// - 如果 base_url 包含 `localhost` / `127.0.0.1` → 归为 `ollama`；
/// - 否则 → `custom`。
pub fn match_vendor_by_base_url(base_url: &str) -> &'static str {
    let s = base_url.trim().to_lowercase();
    if s.is_empty() {
        return "custom";
    }
    if s.contains("localhost") || s.contains("127.0.0.1") {
        return "ollama";
    }
    for v in crate::vendors::VENDORS.iter() {
        let vb = v.base_url.to_lowercase();
        if vb.is_empty() {
            continue;
        }
        // 只要 host 段重合即视为同家
        let host_of = |u: &str| -> String {
            u.trim_start_matches("http://")
                .trim_start_matches("https://")
                .split('/')
                .next()
                .unwrap_or("")
                .to_string()
        };
        if host_of(&s) == host_of(&vb) {
            return v.id;
        }
    }
    "custom"
}

fn default_source_strategy() -> String {
    "studio".to_string()
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AppSettings {
    #[serde(default)]
    pub default_novel_path: String,
    #[serde(default)]
    pub recent_novels: Vec<String>,
    #[serde(default)]
    pub vendors: HashMap<String, VendorConfig>,
    #[serde(default)]
    pub active_vendor: String,
    #[serde(default)]
    pub review_vendor: String,
    #[serde(default, alias = "assistant_vendor")]
    pub writing_vendor: String,
    #[serde(default = "default_source_strategy")]
    pub source_strategy: String,
    #[serde(default)]
    pub writing_streaming: bool,
    #[serde(default)]
    pub review_streaming: bool,
    /// 定时写作前先调用「审计 LLM」对最新一章做一次审计。
    #[serde(default)]
    pub auto_gen_audit_first: bool,
    /// 章节字数目标允许的浮动（绝对字数）。0 表示不启用字数治理。
    #[serde(default = "default_word_tolerance")]
    pub word_tolerance: i32,
    /// 字数归一化是否在保存前自动执行（true 仅追加 prompt，不会自动调用 LLM）。
    #[serde(default)]
    pub word_normalize_on_save: bool,
    /// 章节手动保存成功后，自动串联一次「AI 刷新全部长期记忆档案」。
    ///
    /// 桌面端保留章节手动保存的语义，不自动落盘章节正文；但长期记忆档案
    /// （current_state / pending_hooks / subplot_board / emotional_arcs /
    /// character_matrix / particle_ledger / novel_brief / chapter_summaries）
    /// 若不跟随章节推进同步，会导致后续「生成下一章」的 `[连续性档案]`
    /// 仍是上一章之前的旧状态。此开关默认启用，避免前文错位。
    #[serde(default = "default_auto_refresh_state")]
    pub auto_refresh_state_after_chapter_save: bool,
    /// 生成下一章时是否跳过“等待长期记忆刷新完成”的门控以提升响应速度。
    #[serde(default)]
    pub fast_generate_next_chapter: bool,
    /// Agent 维度的 vendor / model 路由表。
    #[serde(default)]
    pub agent_routing: crate::agent_routing::AgentRoutingTable,
    /// 通知配置（Telegram / 飞书 / 企业微信 / Webhook）。
    #[serde(default)]
    pub notify: crate::notify::NotifyConfig,
    /// 是否已把遗留的 `~/.inkos/.env` 一次性迁移为 Studio vendor。
    /// 首启迁移成功后会置 true 并把原文件改名归档，之后不再读取全局 .env。
    #[serde(default)]
    pub migrated_global_env: bool,
}

fn default_word_tolerance() -> i32 {
    350
}

fn default_auto_refresh_state() -> bool {
    true
}

impl AppSettings {
    /// 字数容差实际生效值（如 settings 中为 0，则取默认 350 而不是 0）。
    pub fn effective_word_tolerance(&self) -> i32 {
        if self.word_tolerance > 0 {
            self.word_tolerance
        } else {
            default_word_tolerance()
        }
    }
}

pub struct ConfigPaths {
    pub home: PathBuf,
}

impl ConfigPaths {
    pub fn new() -> Self {
        Self {
            home: dirs::home_dir().unwrap_or_else(|| PathBuf::from(".")),
        }
    }

    pub fn inkos_dir(&self) -> PathBuf {
        self.home.join(".inkos")
    }

    pub fn desktop_dir(&self) -> PathBuf {
        self.home.join(".inkoswin")
    }

    pub fn global_env_path(&self) -> PathBuf {
        self.inkos_dir().join(".env")
    }

    pub fn settings_path(&self) -> PathBuf {
        self.desktop_dir().join("settings.json")
    }

    pub fn novel_env_path(&self, novel_root: &Path) -> PathBuf {
        novel_root.join(".env")
    }

    /// 读取 `~/.inkos/.env` 的 LLM 配置。仅在「首启迁移」和 UI 只读展示中使用。
    /// 迁移完成后该文件被归档为 `.env.migrated-*`，此函数返回空配置。
    pub fn load_global_config(&self) -> LlmConfig {
        config_from_env(&parse_env_file(&self.global_env_path()))
    }

    pub fn load_novel_config(&self, novel_root: &Path) -> LlmConfig {
        config_from_env(&parse_env_file(&self.novel_env_path(novel_root)))
    }

    #[allow(dead_code)]
    pub fn load_effective_config(&self, novel_root: &Path) -> LlmConfig {
        let g = self.load_global_config();
        let n = self.load_novel_config(novel_root);
        n.resolved_with(&g)
    }

    /// 废弃：不再作为主配置源。保留用于可能的手工回滚场景。
    #[allow(dead_code)]
    pub fn save_global_config(&self, config: &LlmConfig) -> Result<()> {
        self.save_merged_env(&self.global_env_path(), config)
    }

    pub fn save_novel_config(&self, novel_root: &Path, config: &LlmConfig) -> Result<()> {
        self.save_merged_env(&self.novel_env_path(novel_root), config)
    }

    fn save_merged_env(&self, path: &Path, config: &LlmConfig) -> Result<()> {
        let mut existing = parse_env_file(path);
        let known = known_env_keys();
        existing.retain(|k, _| !known.contains(k.as_str()));
        for (k, v) in config.to_env_map() {
            existing.insert(k, v);
        }
        if existing.is_empty() {
            let _ = fs::remove_file(path);
            return Ok(());
        }
        write_env_file(path, &existing)
    }

    #[allow(dead_code)]
    pub fn load_settings(&self) -> AppSettings {
        self.load_settings_with_warning().0
    }

    /// 加载 settings.json；解析失败不直接丢弃数据，而是把损坏文件重命名为
    /// `settings.json.corrupt-<unix_ts>` 备份，然后返回 default。
    /// 第二个返回值是可选的警告串（非空时 UI 应挂到状态栏 / eprintln）。
    pub fn load_settings_with_warning(&self) -> (AppSettings, Option<String>) {
        let p = self.settings_path();
        let fresh = || {
            let mut s = AppSettings::default();
            s.auto_refresh_state_after_chapter_save = default_auto_refresh_state();
            s.word_tolerance = default_word_tolerance();
            s
        };
        let Ok(txt) = fs::read_to_string(&p) else {
            return (fresh(), None);
        };
        match serde_json::from_str::<AppSettings>(&txt) {
            Ok(s) => (s, None),
            Err(e) => {
                let ts = std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_secs())
                    .unwrap_or(0);
                let backup = p.with_extension(format!("json.corrupt-{ts}"));
                let moved = fs::rename(&p, &backup).is_ok();
                let warn = if moved {
                    format!(
                        "settings.json 解析失败（{e}），已备份到 {}",
                        backup.display()
                    )
                } else {
                    format!("settings.json 解析失败：{e}")
                };
                eprintln!("[inkos] {warn}");
                (fresh(), Some(warn))
            }
        }
    }

    /// 归档全局 `.env`：改名为 `.env.migrated-<unix_ts>`，避免下次启动重复迁移。
    fn archive_global_env(&self) -> Option<PathBuf> {
        let src = self.global_env_path();
        if !src.exists() {
            return None;
        }
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        let dst = self.inkos_dir().join(format!(".env.migrated-{ts}"));
        match fs::rename(&src, &dst) {
            Ok(()) => Some(dst),
            Err(e) => {
                eprintln!("[inkos] archive global .env failed: {e}");
                None
            }
        }
    }

    /// 首启迁移：把 `~/.inkos/.env` 作为一个 Studio vendor 导入到 `settings.vendors`。
    ///
    /// 行为：
    /// - 若 `settings.migrated_global_env == true`，直接返回 None。
    /// - 若全局 .env 不存在或没有有效 LLM 字段，仅标记 `migrated_global_env=true` 并落盘。
    /// - 否则按 base_url 匹配 vendor 预设（匹配不到归 `custom`），仅在该 id 当前不存在于
    ///   `settings.vendors` 时插入，避免覆盖用户已有配置。
    /// - 若 `writing_vendor` / `review_vendor` 为空，则设为该 id。
    /// - 成功后把 `.env` 改名归档，并 `save_settings`。
    ///
    /// 返回：`Some(导入的 vendor id)` 代表本次确实导入了一个新 vendor。
    pub fn migrate_global_env_if_needed(&self, settings: &mut AppSettings) -> Option<String> {
        if settings.migrated_global_env {
            return None;
        }
        let env_path = self.global_env_path();
        let llm = if env_path.exists() {
            config_from_env(&parse_env_file(&env_path))
        } else {
            LlmConfig::default()
        };
        let has_any = !llm.base_url.trim().is_empty()
            || !llm.api_key.trim().is_empty()
            || !llm.model.trim().is_empty();

        let imported_id = if has_any {
            let id = match_vendor_by_base_url(&llm.base_url).to_string();
            let mut cfg = VendorConfig::from_llm(&llm);
            // 若 .env 没写 model，但能匹配到预设，则用预设默认 model 兜底
            if cfg.model.is_empty() {
                if let Some(p) = crate::vendors::find(&id) {
                    cfg.model = p.default_model.to_string();
                }
            }
            // 若 .env 没写 base_url 但匹配到预设（极少见），用预设兜底
            if cfg.base_url.is_empty() {
                if let Some(p) = crate::vendors::find(&id) {
                    cfg.base_url = p.base_url.to_string();
                }
            }
            settings.vendors.entry(id.clone()).or_insert(cfg);
            if settings.writing_vendor.trim().is_empty() {
                settings.writing_vendor = id.clone();
            }
            if settings.review_vendor.trim().is_empty() {
                settings.review_vendor = id.clone();
            }
            if settings.active_vendor.trim().is_empty() {
                settings.active_vendor = id.clone();
            }
            Some(id)
        } else {
            None
        };

        settings.migrated_global_env = true;
        // 改名归档 .env（即使 LLM 字段全空，也标记迁移完成避免反复扫描）
        if env_path.exists() {
            let _ = self.archive_global_env();
        }
        if let Err(e) = self.save_settings(settings) {
            eprintln!("[inkos] save settings after migration failed: {e}");
        }
        imported_id
    }

    pub fn save_settings(&self, settings: &AppSettings) -> Result<()> {
        fs::create_dir_all(self.desktop_dir()).ok();
        let txt = serde_json::to_string_pretty(settings)?;
        let final_path = self.settings_path();
        let tmp_path = final_path.with_extension("json.tmp");
        fs::write(&tmp_path, &txt)
            .with_context(|| format!("write tmp {:?}", tmp_path))?;
        if let Err(e) = fs::rename(&tmp_path, &final_path) {
            // Windows 上偶尔 rename 到已存在文件失败，回退为先删后写。
            let _ = fs::remove_file(&final_path);
            fs::rename(&tmp_path, &final_path)
                .with_context(|| format!("rename {:?} -> {:?} ({e})", tmp_path, final_path))?;
        }
        Ok(())
    }
}

pub fn normalize_path(raw: &str) -> Option<PathBuf> {
    let s = raw.trim();
    if s.is_empty() {
        return None;
    }
    let p = if let Some(rest) = s.strip_prefix("~/") {
        dirs::home_dir()?.join(rest)
    } else if s == "~" {
        dirs::home_dir()?
    } else {
        PathBuf::from(s)
    };
    dunce::canonicalize(&p).ok()
}

pub fn unique_paths(items: &[String]) -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for item in items {
        let Some(n) = normalize_path(item) else {
            continue;
        };
        let key = n.to_string_lossy().to_lowercase();
        if seen.insert(key) {
            out.push(n.to_string_lossy().to_string());
        }
    }
    out
}
